language: cpp
sudo: required

matrix:
  fast_finish: true
  include:
  - os: linux
    compiler: gcc
    dist: trusty
    env: BUILD_TYPE=Debug BUILD_CODE=true
    name: Debug build
  - os: linux
    compiler: gcc
    dist: trusty
    env: BUILD_TYPE=Release BUILD_CODE=true
    name: Release build

script:
    cd $HOME
    && sudo apt-get install -y mpich
    && ln -s ${TRAVIS_BUILD_DIR}/support/Machines/bundled_${BUILD_TYPE}.cmake ${TRAVIS_BUILD_DIR}/cmake/machine.cmake
    && mkdir build_${TRAVIS_OS_NAME}_${BUILD_TYPE}
    && cd ./build_${TRAVIS_OS_NAME}_${BUILD_TYPE}
    && cmake ${TRAVIS_BUILD_DIR} -DCMAKE_C_FLAGS=-std=c99
    && make -j1
    && ctest -V
